# Generated by Django 6.0.7 on 2026-07-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('team', 'full_name')},
        ),
        migrations.AlterField(
            model_name='repository',
            name='full_name',
            field=models.CharField(help_text="owner/repo, e.g. 'razorpay/checkout'", max_length=255),
        ),
        migrations.RemoveField(
            model_name='repository',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='last_synced_at',
        ),
    ]
