# Generated by Django 6.0.7 on 2026-07-22 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0002_alter_repository_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repository',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
